{
 "title": "Sensor Data",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Motion Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    value\nFROM\n    motion_sensor_data\n-- WHERE\n--     $__timeFilter(time)  -- Use Grafana's macro for time filtering\nORDER BY\n    time;\n"
    }
   ]
  },
  {
   "title": "Temperature Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    value\nFROM\n    temperature_sensor_data\n-- WHERE\n--     $__timeFilter(time)  -- Use Grafana's macro for time filtering\nORDER BY\n    time;\n"
    }
   ]
  },
  {
   "title": "Smoke Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    smoke\nFROM\n    smoke_sensor_data \n-- WHERE\n--     $__timeFilter(time)  -- Use Grafana's macro for time filtering\nORDER BY\n    time;\n"
    }
   ]
  },
  {
   "title": "CO Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    co_level\nFROM\n    smoke_sensor_data \n-- WHERE\n--     $__timeFilter(time)  -- Use Grafana's macro for time filtering\nORDER BY\n    time;\n"
    }
   ]
  },
  {
   "title": "Temperature Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    value\nFROM\n    temperature_sensor_data\n-- WHERE\n--     $__timeFilter(time)  -- Use Grafana's macro for time filtering\nORDER BY\n    time;\n"
    }
   ]
  }
 ]
}